import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navber from "@/components/Navber/Navber";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navber />
        <div className="w-full h-full bg-slate-100">
           {children}
        </div>
       
        <Footer />
      </body>
    </html>
  );
}
